;;; -*- mode: lisp; package: user -*-
;;;
;;; File: layered-window.l
;;;
;;; License:
;;;
;;;   Copyright (c) 2003-2007 MIYAMUKO Katsuyuki.
;;;
;;;   layered-window is released under an MIT license.
;;;   See layered-window/docs/MIT-LICENSE for full license.
;;;

(in-package :user)

(require "layered-window/api")
(require "layered-window/api/compat")

#+xyzzy
(require "layered-window/editor")


(provide "layered-window")

;;; End
