;;; -*- mode: lisp; package: user -*-
;;;
;;; File: layered-window/ffi.l
;;;
;;; License:
;;;
;;;   Copyright (c) 2003-2007 MIYAMUKO Katsuyuki.
;;;
;;;   layered-window is released under an MIT license.
;;;   See layered-window/docs/MIT-LICENSE for full license.
;;;

(in-package :user)

(require "layered-window/ffi/package")
(require "layered-window/ffi/types")
(require "layered-window/ffi/user32")
(require "layered-window/ffi/kernel32")

(provide "layered-window/ffi")

;;; End
